TP-13f added routing
frontend-park-mail-ru/2024_2_bogo_sort pull request #12
Opened 2024-11-15 21:43 UTC by chsd0

2024-11-16 10:36 UTC, erik770 requested changes
1. не забывай линтер прогонять перед коммитами)
2. сделай поиск по приложению по window.location.href, еще много где используется
3. убери лишние импорты в файлах (много где initHeaderAndMain осталось)
4. саму функцию initHeaderAndMain тоже можно удалить теперь

2024-11-16 10:36 UTC, erik770 commented on server/server.js
> +app.get('/edit/:id', (req, res) => {
тут вроде регулярку хотели сделать

2024-11-16 10:36 UTC, erik770 commented on src/components/obyavlenie/obyavlenie.js
> +            sellerName: sellerUser.username,
с бека стало приходить 'Пользователь'?

2024-11-16 10:36 UTC, erik770 commented on src/components/obyavlenie/obyavlenie.js
> +            window.location.href = `/edit/${advertId}`;
а как же роутер?

2024-11-16 10:36 UTC, erik770 commented on src/constants/constants.js
> +    },
нет же logout страницы, щас если в адресную строку ввести /logout то выкинет из аккаунта. мне кажется такого поведения не должно быть

2024-11-16 10:36 UTC, erik770 commented on src/index.js
>      }
а если на click list__icon в месте где он находится навесить stopPropogation и обернуть list__icon тегом а, не сработает?

2024-11-16 10:36 UTC, erik770 commented on src/modules/routing.js
>  class Routing {
давай переименуем на Router

2024-11-16 10:36 UTC, erik770 commented on src/modules/routing.js
> +        }
смотри, мне не нравится что роутер у нас что-то знает о хедере вообще и структуре нашей страницы, потому что роутер это что-то абстрактное, универсальное и переиспользуемое.

Есть мысль инициализировать хедер и мейн вне роутера (например там где ты делаешь router.init(); + передавать в роутер ноду внутри которой ты будешь менять контент (в нашем случае div.main)

2024-11-16 10:36 UTC, erik770 commented on src/modules/routing.js
> +export default new Routing();
export default -- плохая практика

https://basarat.gitbook.io/typescript/main-1/defaultisbad
https://www.reddit.com/r/javascript/comments/hg3wl4/is_using_default_exports_considered_a_bad/

2024-11-16 10:36 UTC, erik770 commented on src/pages/advertCreate/advertCreate.js
> -        const main = initHeaderAndMain();
убираем все что не используется (initHeaderAndMain)

2024-11-16 16:40 UTC, chsd0 commented on src/components/obyavlenie/obyavlenie.js
> +            sellerName: sellerUser.username,
нет, надо будет попросить сделать дефолтный юзернейм

2024-11-16 17:32 UTC, chsd0 commented on src/index.js
>      }
нет, так не получилось, а list__icon уже обернут а

2024-11-17 15:22 UTC, erik770 reviewed
микроштуки остались

2024-11-17 15:22 UTC, erik770 commented on src/components/header/header.js
> +            // router.goToPage('/');
комент остался

2024-11-17 15:22 UTC, erik770 commented on src/components/header/header.js
> +        const logoutButton = this.#wrapper.querySelector('#Выйти');
1. нехорошо по словам на русском селектить и вообще использовать их в коде (коменты исключение)
2. если щас кто-то решит кнопку переименовать в "выход" то селектор отвалится. нехорошо ориентироваться на какие-то строчки

2024-11-17 15:22 UTC, erik770 commented on src/constants/constants.js
> +    },
вроде на выход навесил вызов функции но тут забыл убрать. и LogoutPage удалить

2024-11-17 15:22 UTC, erik770 commented on src/constants/constants.js
> +            redirectUrl: '#'
мб '/'? а для селекта можно флаг опциональный например добавить isLogout

2024-11-17 15:46 UTC, erik770 commented on src/index.js
>      }
странно конечно(( давай тогда костыль хотяб перенесем туда, а не чтобы он был в index.js

2024-11-18 19:54 UTC, erik770 commented on src/components/header/header.scss
> -    &__link {
можно было оставить и menu__link и menu__link-smth

2024-11-18 19:54 UTC, erik770 commented on src/components/header/header.hbs
> +                <a class="menu__link-{{this.engName}}" href="{{this.redirectUrl}}" id="{{this.name}}"><img class="menu__icon" src="{{this.iconUrl}}">{{this.name}}</a>
если id не используется то можно убрать

2024-11-18 20:02 UTC, erik770 approved these changes

2024-11-18 20:03 UTC, merged